name: ci
on: pull_request

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
         java-version: adopt@1.11

      - name: Install python dependencies
        run: |
          pip install wheel~=0.34.2
          pip install twine
          pip install -r python-package/requirements.txt

      - name: Run tests
        run: |
          make all
          make test
